repos:
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-4
    hooks:
      - id: shfmt
        args: ["-i", "2", "-ci", "-bn"]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
